
if (TARGET CONAN_LIB::protobuf_libprotocddebug)
    get_target_property(Protobuf_PROTOC_LIBRARY_DEBUG CONAN_LIB::protobuf_libprotocddebug INTERFACE_LINK_LIBRARIES)
    get_target_property(Protobuf_LIBRARY_DEBUG CONAN_LIB::protobuf_libprotobufddebug INTERFACE_LINK_LIBRARIES)
    get_target_property(Protobuf_PROTOC_LIBRARY CONAN_LIB::protobuf_libprotocrelwithdebinfo INTERFACE_LINK_LIBRARIES)
    get_target_property(Protobuf_LIBRARY CONAN_LIB::protobuf_libprotobufrelwithdebinfo INTERFACE_LINK_LIBRARIES)
    set(Protobuf_INCLUDE_DIR ${CONAN_INCLUDE_DIRS_PROTOBUF_DEBUG})
    set(Protobuf_PROTOC_EXECUTABLE "${CONAN_PROTOBUF_ROOT_DEBUG}/bin/protoc${CMAKE_EXECUTABLE_SUFFIX}")
else ()
    if (TARGET CONAN_LIB::protobuf_protocd)
        get_target_property(Protobuf_PROTOC_LIBRARY_DEBUG CONAN_LIB::protobuf_protocd INTERFACE_LINK_LIBRARIES)
        get_target_property(Protobuf_PROTOC_LIBRARY CONAN_LIB::protobuf_protocd INTERFACE_LINK_LIBRARIES)
        get_target_property(Protobuf_INCLUDE_DIR CONAN_LIB::protobuf_protobufd INCLUDE_DIRECTORIES)
    endif ()
    if (TARGET CONAN_LIB::protobuf_protobuf)
        get_target_property(Protobuf_LIBRARY_DEBUG CONAN_LIB::protobuf_protobuf INTERFACE_LINK_LIBRARIES)
        get_target_property(Protobuf_LIBRARY CONAN_LIB::protobuf_protobuf INTERFACE_LINK_LIBRARIES)
        get_target_property(Protobuf_INCLUDE_DIR CONAN_LIB::protobuf_protobuf INCLUDE_DIRECTORIES)
    endif ()

    set(Protobuf_PROTOC_EXECUTABLE "${CONAN_PROTOBUF_ROOT}/bin/protoc${CMAKE_EXECUTABLE_SUFFIX}")
endif ()

include(FindProtobuf)
message("-- Protobuf_INCLUDE_DIR=${Protobuf_INCLUDE_DIR}")
message("-- Protobuf_PROTOC_EXECUTABLE=${Protobuf_PROTOC_EXECUTABLE}")
